# Generated by Django 3.0.3 on 2020-04-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='post',
            name='video_link',
            field=models.URLField(blank=True, max_length=600),
        ),
    ]
