# Generated by Django 3.0.3 on 2020-04-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment_likes',
            field=models.ManyToManyField(blank=True, to='forum.Comment'),
        ),
    ]
