# Generated by Django 3.0.3 on 2020-04-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_user_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image_link',
            field=models.URLField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, max_length=3000),
        ),
    ]
