# Generated by Django 3.0.3 on 2020-05-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200430_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(blank=True, max_length=8000),
        ),
    ]
